# Generated by Django 2.2.4 on 2020-02-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Project Name')),
                ('user_id', models.IntegerField(verbose_name='User id')),
                ('saved', models.TextField(verbose_name='Project Output')),
            ],
        ),
    ]
